[start]
command:/usr/local/opnsense/scripts/wg-quic/service-control.php
parameters:start %s
type:script
message:starting wg-quic instance %s

[stop]
command:/usr/local/opnsense/scripts/wg-quic/service-control.php
parameters:stop %s
type:script
message:stopping wg-quic instance %s

[restart]
command:/usr/local/opnsense/scripts/wg-quic/service-control.php
parameters:restart %s
type:script
message:restarting wg-quic instance %s
description:Restart wg-quic

[reload]
command:/usr/local/opnsense/scripts/wg-quic/service-control.php
parameters:configure %s
type:script
message:reloading wg-quic

[configure]
command:/usr/local/opnsense/scripts/wg-quic/service-control.php
parameters:configure %s
type:script
message:configuring wg-quic instances (%s)

[status]
command:/usr/local/opnsense/scripts/wg-quic/service-control.php
parameters:status %s
type:script_output
message:requesting wg-quic status

[show]
command:/usr/local/opnsense/scripts/wg-quic/show.py
type:script_output
message:requesting wg-quic tunnel status

[version]
command:/usr/local/opnsense/scripts/wg-quic/version.py
type:script_output
message:requesting wg-quic version

[keypair]
command:/usr/local/opnsense/scripts/wg-quic/keys.py
parameters:keypair
type:script_output
message:generating wg-quic keypair

[psk]
command:/usr/local/opnsense/scripts/wg-quic/keys.py
parameters:psk
type:script_output
message:generating wg-quic pre-shared key
