###################################################################
# Local syslog-ng configuration filter definition [wireguardquic].
###################################################################
filter f_local_wireguardquic {
    program("wg-quic");
};
