PLUGIN_NAME=		wg-quic
PLUGIN_VERSION=		0.1.0
PLUGIN_COMMENT=		wg-quic userspace VPN integration
PLUGIN_MAINTAINER=	rc-chn@users.noreply.github.com
PLUGIN_LICENSE=		GPLv3

.include "../../Mk/plugins.mk"
