PLUGIN_NAME=		wg-quic
PLUGIN_VERSION?=
.if empty(PLUGIN_VERSION)
.error PLUGIN_VERSION must be provided from the repository VERSION file
.endif
PLUGIN_COMMENT=		wg-quic userspace VPN integration
PLUGIN_MAINTAINER=	rc-chn@users.noreply.github.com
PLUGIN_LICENSE=		GPLv3

.include "../../Mk/plugins.mk"
